// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-ecommerce-backend-api/internal/controller"
	"go-ecommerce-backend-api/internal/repo"
	"go-ecommerce-backend-api/internal/service/impl"
)

// Injectors from auth.wire.go:

func InitAuthRouterHandler() (*controller.AuthController, error) {
	iUserRepository := repo.NewUserRepository()
	iAuthService := impl.NewAuthService(iUserRepository)
	authController := controller.NewAuthController(iAuthService)
	return authController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iUserAuthRepository := repo.NewUserAuthRepository()
	iUserInfo := impl.NewUserService(iUserRepository, iUserAuthRepository)
	userController := controller.NewUserController(iUserInfo)
	return userController, nil
}
